### ISSUE TITLE
No error message given when commas are not used in an instruction.

### ISSUE THREAD

**Issue by dmcevoy1** [Progressive-Learning-Platform/plpTool-prototype#76]
No error message given when commas are not used in an instruction. It simply prints Java.lang.NullPointerException if comments are missed. Please add an appropriate error message.

**Comment by harsha-kadekar** [comment]
Fixed now.. Assemble function was enclosed by a general try catch blocks, so all exceptions were caught and not reported to main.java functions. Now removed. Also some improvements to the code now for better error handling in assembler
